from elasticsearch import Elasticsearch

es = Elasticsearch(
    cloud_id="usuarios:dXMtZWFzdC0yLmF3cy5lbGFzdGljLWNsb3VkLmNvbSRjMWQ3MzVlZDYyN2I0ZTM4ODMxYTczN2E0NGE1MjNlMCQ5MmZjZjljMjc1YzA0NzRlYWMxZTQ0ZGEwZDEwNDNlZQ=="
)